### ISSUE TITLE
Offscreen scroll image

### ISSUE THREAD

**Issue by necenzurat** [kikinteractive/app#69]
Hello, so i am trying to implement an easter egg like the one in [foursquare app](http://abstractionhub.files.wordpress.com/2013/07/foursquare-refresh-ultimate-scrolldown-2.png) as in  if you scroll enought you can see an image. 

related pic of my super (first) awesome app:
![scroll-image](https://cloud.githubusercontent.com/assets/145449/5795453/311adc90-9f99-11e4-969f-d5874db30b6c.png)

**Comment by jairajs89** [comment]
This should do it:

```css
.app-content:before {
    position: absolute;
    z-index: 1;
    top: -48px; /*enough so the image cant be seen normally*/
    left: 50%;
    margin-left: -16px; /*half of image height*/
    height: 32px; /*image height*/
    width: 32px; /*image width*/
    background-image: url(/path/to/image.png);
    content: "";
}
```

**Comment by necenzurat** [comment]
nope, did not do the trick.

**Comment by jairajs89** [comment]
Ah that version only works on Android 4+, iOS 5+.

A cross platform version requires you to put the easter egg image in the HTML directly:

```html
<div class="app-page">
    <!-- ... -->
    <div class="app-content">
        <div class="easter-egg"></div>
        <!-- ... -->
    </div>
</div>
```

```css
.easter-egg {
    position: absolute;
    z-index: 1;
    top: -48px; /*enough so the image cant be seen normally*/
    left: 50%;
    margin-left: -16px; /*half of image height*/
    height: 32px; /*image height*/
    width: 32px; /*image width*/
    background-image: url(/path/to/image.png);
    content: "";
}
```
