### ISSUE TITLE
App.dialog has the different interface from v2. Why ?  Thanks

### ISSUE THREAD

**Issue by jackyzhong123** [kikinteractive/app#73]

**Comment by jairajs89** [comment]
There has been demand for custom fields in the dialogs. The old implementation was standard on Android but on iPhone was more akin to "action sheets". This difference in presentation makes it difficult to customise or have strong expectations as to how they work.

So the goals for the changes were to unify the interface as well as allow for easy customisation.

**Comment by jackyzhong123** [comment]
Thanks for you reply. If I want the action sheets on iPhone, how can I customize it ?

**Comment by jairajs89** [comment]
Here is an action sheet implementation:

```css
/* put this in your css */
.action-sheet {
    position: absolute;
    bottom: 0;
    left: 0;
    margin: 0;
    padding: 0;
    width: 100%;
    background-color: rgba(255,255,255,0.85);
    border-top: 1px solid #FFF;
    -webkit-box-shadow: 0 0 8px rgba(0,0,0,0.85);
    box-shadow: 0 0 8px rgba(0,0,0,0.85);
    color: #777;
    -webkit-transform: translate3d(0,110%,0);
    transform: translate3d(0,110%,0);
    -webkit-transition: -webkit-transform 0.425s cubic-bezier(0.4,0.6,0.05,1);
    transition: transform 0.425s cubic-bezier(0.4,0.6,0.05,1);
}
.action-sheet.enabled {
    -webkit-transform: translate3d(0,0,0);
    transform: translate3d(0,0,0);
}
.action-sheet .title {
    position: relative;
    margin-bottom: 8px;
    padding: 16px 20px 0;
    font-size: 18px;
    font-weight: 600;
    text-align: center;
}
.action-sheet .button {
    height: 60px;
    color: #17B;
    font-size: 22px;
    font-weight: 300;
    line-height: 60px;
    text-align: center;
}
.action-sheet .button.ok {
    color: #3C7;
}
.action-sheet .button.cancel {
    color: #E54;
}
.action-sheet .button.active {
    opacity: 0.5;
}
```

```html
<!-- put this in your html -->
<div class="action-sheet">
    <div class="title">This is my action sheet</div>
    <div class="app-button ok" data-option="main">Main option</div>
    <div class="app-button" data-option="1">Other option 1</div>
    <div class="app-button" data-option="2">Other option 2</div>
    <div class="app-button cancel" data-option="">Cancel</div>
</div>
```

```js
// put this in your javascript
function ActionSheet(callback) {
    var $sheet = $('.action-sheet');
    $sheet.find('.app-button').clickable().click(function () {
        $sheet.removeClass('enabled');
        callback && callback( $(this).data('option') );
    });
    $sheet.addClass('enabled');
}

// use it like this
ActionSheet(function (option) {
    if (option === 'main') {
        // they clicked the 'main' button
    } else if (option === '1') {
        // they clicked the '1' button
    } // etc
});
```
